mutation backupVirtualMachine ($slaId: String, $id: String!) {
    vsphereOnDemandSnapshot (input: {
        config: {
            slaId: $slaId
        },
        id: $id,
        userNote: ""
    }) {
        id
        status
    }
}