query getVirtualDisk($fid: UUID!) {
    vSphereVmNew (fid:$fid) {
        cdmId
        id
        vsphereVirtualDisks {
            nodes {
                fid
                cdmId
                clusterUuid
                size
                virtualMachineId
                datastoreFid
                datastore {
                    id
                    name
                }
            }
        }
    }
}

#{
#    "fid": "0183505e-c1be-58d5-a1f1-cd0655fca461"
#}