query listVirtualMachines {
    vSphereVmNewConnection {
        count
        nodes {
            cdmId
            id
            name
            cluster {
                name
                id
            }
            effectiveSlaDomain {
                name
                id
            }
            numWorkloadDescendants
        }
    }
}