query SnapshotsListSingleQuery($workloadId: String!) {
    snapshotsListConnection: snapshotOfASnappableConnection(workloadId: $workloadId) {
        nodes {
            id
            date
            expirationDate
            isExpired
            isOnDemandSnapshot
            snappableId
        }
    }
}