mutation vSphereInstantRecoverMutation($id: String!, $snapshotId: String, $disableNetwork: Boolean, $keepMacAddresses: Boolean, $removeNetworkDevices: Boolean, $preserveMoid: Boolean, $powerOn: Boolean) {
    vsphereVmInitiateInstantRecoveryV2(input: {
        id: $id,
        config: {
            requiredRecoveryParameters: {
                snapshotId: $snapshotId
            },
            mountExportSnapshotJobCommonOptionsV2: {
                disableNetwork: $disableNetwork
                keepMacAddresses: $keepMacAddresses,
                powerOn: $powerOn,
                removeNetworkDevices: $removeNetworkDevices
            },
            preserveMoid: $preserveMoid
        }
    }) {
        status
    }
}