mutation updateVirtualMachine ($id: String!, $configuredSlaDomainId: String ) {
    updateVsphereVm (input: {
        id: $id,
        vmUpdateProperties: {
            virtualMachineUpdate: {
                configuredSlaDomainId: $configuredSlaDomainId
            }
        }
    }) {
        success
    }
}